### ISSUE TITLE
intelmqctl: fails to start due to missing dependencies not described in INSTALL

### ISSUE THREAD

**Issue by deadbits** [certtools/intelmq#1412] opened 2019-06-02 14:49 UTC
I followed the installation guide for my OS (Ubuntu 18.04.2), installed the management web UI (which loads and seems to act fine, though bots never _stay_ running. I think the crux of the issue is that `intelmqctl` doesn't execute properly, regardless of the command it's given.

I'm running Python3.7 - is IntelMQ expecting a different version? I didn't see anything in the documentation other than "python3". 

Also, I can see there's at least one missing Python dependency `apt_pkg`, after running `sudo apt-get install python3-apt` to install the package it still doesn't seem to find. Neither this package nor `apport` are in the INSTALL documentation so I'm not sure where to go from here.. Any help would be much appreciated

**Error Ouput**
```
intelmq@threat-intel:~$ intelmqctl -h
Traceback (most recent call last):
  File "/usr/local/bin/intelmqctl", line 6, in <module>
    from intelmq.bin.intelmqctl import main
  File "/usr/local/lib/python3.7/dist-packages/intelmq/bin/intelmqctl.py", line 22, in <module>
    import psutil
  File "/usr/lib/python3/dist-packages/psutil/__init__.py", line 100, in <module>
    from . import _pslinux as _psplatform
  File "/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 26, in <module>
    from . import _psutil_linux as cext
ImportError: cannot import name '_psutil_linux' from 'psutil' (/usr/lib/python3/dist-packages/psutil/__init__.py)
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "/usr/local/bin/intelmqctl", line 6, in <module>
    from intelmq.bin.intelmqctl import main
  File "/usr/local/lib/python3.7/dist-packages/intelmq/bin/intelmqctl.py", line 22, in <module>
    import psutil
  File "/usr/lib/python3/dist-packages/psutil/__init__.py", line 100, in <module>
    from . import _pslinux as _psplatform
  File "/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 26, in <module>
    from . import _psutil_linux as cext
ImportError: cannot import name '_psutil_linux' from 'psutil' (/usr/lib/python3/dist-packages/psutil/__init__.py)
```

**Comment by wagner-certat** [comment] 2019-06-03 07:16
That looks like a broken psutil (the error comes at it's import), nothing we could fix here.

**Comment by wagner-certat** [comment] 2019-06-03 07:38
Couldn't reproduce this import error with a plain up-to-date bionic and installing only psutil. Hower search for this error `No module named 'apt_pkg'` gives some results with problem descriptions and solutions for debian/ubuntu. First try would be `sudo apt-get install python3-apt --reinstall`

**Comment by wagner-certat** [comment] 2019-12-06 17:26
No feedback, closing here

**Closed by wagner-certat** 2019-12-06 17:26 UTC
Labels: support
