### ISSUE TITLE
ZeuS, Palevo and Feodo trackers RSS

### ISSUE THREAD

**Issue by robcza** [certtools/intelmq#292] opened 2015-08-20 10:26 UTC
This is a followup to this pull request https://github.com/certtools/intelmq/pull/274
@SYNchroACK I have investigated the RSS feeds (direct links below) and I can see a problem there as all of these feeds include only 20 recently identified hosts and IntelMQ will miss the whole picture.

I think the best way is to prepare both parsers - for the complete lists and for the rss feeds as well. What do you say?

https://zeustracker.abuse.ch/rss.php
https://palevotracker.abuse.ch/?rssfeed
https://feodotracker.abuse.ch/feodotracker.rss

**Comment by aaronkaplan** [comment] 2015-08-20 10:40
I'd say let's go for the complete feed and make the RSS collector as soon a it's needed (for some other feed maybe?).  

My 2 cents. 

---
Mobile

**Comment by robcza** [comment] 2015-08-20 10:54
I have the complete feed ready. I will just retest and could go for pull request.

**Comment by aaronkaplan** [comment] 2015-08-20 17:25
Thanks Robcza!

**Comment by SYNchroACK** [comment] 2015-08-23 11:28
@robcza the following link has all the RSS feed for Zeus:
https://zeustracker.abuse.ch/feeds.php

If the problem is the RSS feed jjust show the last 20 events, well, we just need to configure the collector to get the report every 30 min..... make sense @robcza ?

**Comment by aaronkaplan** [comment] 2015-10-07 11:54
any news on this? I'd be willing to test the RSS bots.

**Comment by SYNchroACK** [comment] 2017-02-01 07:08
@aaronkaplan @robcza any news or can we close this one since we are handling the Abuse.ch data without RSS feeds.

**Comment by robcza** [comment] 2017-02-02 06:24
We can close, I din't find any use case for the RSS bot. Maybe @aaronkaplan which originally requested that one.

**Comment by wagner-certat** [comment] 2017-02-03 13:46
Closing this. Once we find out that one is needed, please reopen.

**Closed by wagner-certat** 2017-02-03 13:46 UTC
Labels: component: bots, feature request
