### ISSUE TITLE
Clarification about "enabled" switch

### ISSUE THREAD

**Issue by sykaeh** [certtools/intelmq#825] opened 2016-12-15 16:59 UTC
Issue #715 introduced an enabled switch and as far as I understood this was another parameter of the bot (i.e. like `rate_limit` or `hierarchical_output`) that could be used for any bot (or is it only collectors?). This is also documented in [Bots.md](https://github.com/certtools/intelmq/blob/b5c87cafb6be758963714978fb114d3a0dc39239/docs/Bots.md).

However, when I tried to use the enabled parameter, it did not do anything. Looking into the source code, the changes in 06cde54d914ff4d025d012980fa003fe318cf990 seem to show that the enabled flag is one level higher (on the same level as `name` and `module`). Is there an error in the code or in the documentation?

**Comment by dmth** [comment] 2016-12-16 09:26
I cannot tell you why it's not working. The changeset you are referencing ist for intelmqctl. The switch you most likely refer to was introduced here https://github.com/certtools/intelmq/commit/9d0db8aa1c9ce325e81d7841834034f3f6f4ccd7 and was genralised here https://github.com/certtools/intelmq/commit/2828cf6b90f5d18c07ca4246bf408117f22fcbe2

**Comment by ondj** [comment] 2016-12-19 14:06
I think that the problem is in [this code](https://github.com/certtools/intelmq/blob/66eb8f2bbac9cfbd538529b5e5b70ae37976cd00/intelmq/bin/intelmqctl.py#L463):
```python
    def botnet_start(self):
        botnet_status = {}
        for bot_id in sorted(self.runtime_configuration.keys()):
            if self.runtime_configuration[bot_id].get('enabled', True):
```

Because `enabled` is loaded directly from `runtime_configuration`  and not from `parameters` array.

**Comment by sebix** [comment] 2016-12-20 09:31
As enabled is not related to the parameters for the bot itself, but rather for the initialization (just as module), I think this behavior is fine.

**Comment by ondj** [comment] 2016-12-20 14:59
Sorry, now I get it. So maybe it could help when `enabled` will be added to all bots in BOTS file with `true` value?

**Comment by sykaeh** [comment] 2016-12-20 15:21
So, to summarize:
1. The enabled switch is only used in the `intelmqctl` (it was removed from the other places in 408b969)
2. The enabled switch is part of the initialization of the bot, so it should be added at that level. For example (in `runtime.conf`):
```
    "shadowserver-parser": {
        "group": "Parser",
        "name": "ShadowServer",
        "module": "intelmq.bots.parsers.shadowserver.parser",
        "description": "ShadowServer parses the shadowserver reports.",
        "parameters": {
            "feedname": ""
            "overwrite": false
        },
       "enabled": true
    },
```

Is this information correct?

If it is, then the documentation should be adjusted in the following places:

1. [BOTS.md](https://github.com/certtools/intelmq/blob/4303ee7de6c64ff1c55c592f1b7c5ecc98fe7cdb/docs/Bots.md): The section about the enabled switch should be removed or clarified that it is not like the other parameters and needs to be added a level higher.
2. [User-Guide.md](https://github.com/certtools/intelmq/blob/4303ee7de6c64ff1c55c592f1b7c5ecc98fe7cdb/docs/User-Guide.md#runtime-configuration): The runtime configuration should be adjusted to have the "enabled" setting.
3. [BOTS](https://github.com/certtools/intelmq/blob/4303ee7de6c64ff1c55c592f1b7c5ecc98fe7cdb/intelmq/bots/BOTS): The BOTS file should be adjusted to have the "enabled" setting for all bots.

**Comment by sebix** [comment] 2016-12-20 15:44
Docs: yes, that's what this issue is about, isn't it?

> BOTS: The BOTS file should be adjusted to have the "enabled" setting for all bots.

Default is true. I don't see any reason why we should add default and clutter up the config.

**Comment by SYNchroACK** [comment] 2016-12-29 03:35
@sykaeh 

> 1. [BOTS.md](https://github.com/certtools/intelmq/blob/4303ee7de6c64ff1c55c592f1b7c5ecc98fe7cdb/docs/Bots.md): The section about the enabled switch should be removed or clarified that it is not like the other parameters and needs to be added a level higher.

I agree with you regarding the clarification but the `enabled` parameter is like other parameter except the fact that is useful across all types of bots (collector, parser, expert and output) and that's the reason that makes sense to be documented in the beginning of the documentation (like it is currently). IMHO the clarification should include the detail that the `enabled` parameter is like other parameter, therefore needs to be specified in each bot in case has a different value than the value specified in defaults.conf (which currently is not specified, see bellow...)

> 2. [User-Guide.md](https://github.com/certtools/intelmq/blob/4303ee7de6c64ff1c55c592f1b7c5ecc98fe7cdb/docs/User-Guide.md#runtime-configuration): The runtime configuration should be adjusted to have the "enabled" setting.

IMHO no. It's a parameter that most of the times will have the value `True` and applies to each bot. My suggestion is to add the `enabled` parameter to default.conf file to be clear for everyone that the parameter exist and the default value specified is `True`.

> 3. [BOTS](https://github.com/certtools/intelmq/blob/4303ee7de6c64ff1c55c592f1b7c5ecc98fe7cdb/intelmq/bots/BOTS): The BOTS file should be adjusted to have the "enabled" setting for all bots.

Nop. Generic parameters like this one MUST NOT be added to BOTS file.

> 4. IntelMQ-Manager: The manager should be updated to be able to set the "enabled" setting: See certtools/intelmq-manager#92.

This is a know issue of manager. The current behavior is:
* you add a bot through the manager and you only see the options specified in BOTS file during that action ("Add Bot").
* in case you want to change a value in a specific bot from a parameter that is declared on defaults.conf, you can do it through the manager using the "Edit Bot" action, since it will show you all parameters from defaults.conf and runtime.conf.
* in case you want to change the defaults.conf in order to have a parameter with a default value, you can only do it editing manually the file.

@sykaeh let me know if you agree with my comments in order to fix and close this issue :) Cheers!

**Comment by sykaeh** [comment] 2017-01-03 08:22
I would not add it to `defaults.conf` because it is not like any other parameter. It is more like `name`, `description` or `module` attributes of the bot. I think if we added it to `defaults.conf` it would just add more to the confusion that created this issue.

I would also stop referring to it as a bot parameter as it is not like the other parameters. It is more like a status of a bot.

**Closed** 2017-01-13 19:03 UTC
Labels: bug, documentation
