### ISSUE TITLE
Doc - Improve DataHarmonization.md

### ISSUE THREAD

**Issue by Phantasus** [certtools/intelmq#189] opened 2015-05-29 14:03 UTC
Hi,

DataHarmonization.md reads clumsy and not that well formulated. As this is a very important
document it must be clear to understand. After reading it I still felt not to get "it".

I will add the relevant sections, which in my opinion need better explanation.

**Comment by SYNchroACK** [comment] 2015-05-31 00:52
@Phantasus agree with you! Send the proposal, it will be really helpful for community.

**Comment by sebix** [comment] 2015-08-20 08:22
Duplicate of #185

**Closed** 2015-09-11 13:53 UTC
Labels: duplicate
