### ISSUE TITLE
unittests failing

### ISSUE THREAD

**Issue by sashank** [certtools/intelmq#714] opened 2016-09-27 10:18 UTC
just downloaded intelmq and installed all the steps on ubuntu 14.04.4 
am trying to ensure if all is good , the below errors appear while running unit tests 
Either some install steps are missing or some additional steps are needed. any help would be great ! 

```
ubuntu05:/home/intelmq/intelmq$ python3 -m unittest
======================================================================
ERROR: intelmq.tests.bots.collectors.blueiv.test_collector (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/usr/lib/python3.4/unittest/case.py", line 577, in run
    testMethod()
  File "/usr/lib/python3.4/unittest/loader.py", line 32, in testFailure
    raise exception
ImportError: Failed to import test module: intelmq.tests.bots.collectors.blueiv.test_collector
Traceback (most recent call last):
  File "/usr/lib/python3.4/unittest/loader.py", line 312, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.4/unittest/loader.py", line 290, in _get_module_from_name
    __import__(name)
  File "/home/intelmq/intelmq/intelmq/tests/bots/collectors/blueiv/test_collector.py", line 6, in <module>
    import intelmq.bots.collectors.blueliv.collector_crimeserver
  File "/home/intelmq/intelmq/intelmq/bots/collectors/blueliv/collector_crimeserver.py", line 8, in <module>
    from sdk.blueliv_api import BluelivAPI
ImportError: No module named 'sdk'

======================================================================
ERROR: intelmq.tests.bots.collectors.n6.test_collector (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/usr/lib/python3.4/unittest/case.py", line 577, in run
    testMethod()
  File "/usr/lib/python3.4/unittest/loader.py", line 32, in testFailure
    raise exception
ImportError: Failed to import test module: intelmq.tests.bots.collectors.n6.test_collector
Traceback (most recent call last):
  File "/usr/lib/python3.4/unittest/loader.py", line 312, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.4/unittest/loader.py", line 290, in _get_module_from_name
    __import__(name)
  File "/home/intelmq/intelmq/intelmq/tests/bots/collectors/n6/test_collector.py", line 6, in <module>
    import intelmq.bots.collectors.n6.collector_stomp
  File "/home/intelmq/intelmq/intelmq/bots/collectors/n6/collector_stomp.py", line 14, in <module>
    class StompListener(stomp.listener.PrintingListener):
AttributeError: 'NoneType' object has no attribute 'listener'


======================================================================
ERROR: intelmq.tests.bots.collectors.rt.test_collector (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/usr/lib/python3.4/unittest/case.py", line 577, in run
    testMethod()
  File "/usr/lib/python3.4/unittest/loader.py", line 32, in testFailure
    raise exception
ImportError: Failed to import test module: intelmq.tests.bots.collectors.rt.test_collector
Traceback (most recent call last):
  File "/usr/lib/python3.4/unittest/loader.py", line 312, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.4/unittest/loader.py", line 290, in _get_module_from_name
    __import__(name)
  File "/home/intelmq/intelmq/intelmq/tests/bots/collectors/rt/test_collector.py", line 5, in <module>
    import intelmq.bots.collectors.rt.collector_rt
  File "/home/intelmq/intelmq/intelmq/bots/collectors/rt/collector_rt.py", line 11, in <module>
    import rt
ImportError: No module named 'rt'


======================================================================
ERROR: intelmq.tests.bots.collectors.xmpp.test_collector (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/usr/lib/python3.4/unittest/case.py", line 577, in run
    testMethod()
  File "/usr/lib/python3.4/unittest/loader.py", line 32, in testFailure
    raise exception
ImportError: Failed to import test module: intelmq.tests.bots.collectors.xmpp.test_collector
Traceback (most recent call last):
  File "/usr/lib/python3.4/unittest/loader.py", line 312, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.4/unittest/loader.py", line 290, in _get_module_from_name
    __import__(name)
  File "/home/intelmq/intelmq/intelmq/tests/bots/collectors/xmpp/test_collector.py", line 5, in <module>
    import intelmq.bots.collectors.xmpp.collector
  File "/home/intelmq/intelmq/intelmq/bots/collectors/xmpp/collector.py", line 101, in <module>
    class XMPPClient(sleekxmpp.ClientXMPP):
AttributeError: 'NoneType' object has no attribute 'ClientXMPP'


======================================================================
ERROR: test (intelmq.tests.bots.experts.gethostbyname.test_expert.TestGethostbynameExpertBot)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/intelmq/intelmq/intelmq/tests/bots/experts/gethostbyname/test_expert.py", line 38, in test
    self.assertMessageEqual(0, EXAMPLE_OUTPUT)
  File "/home/intelmq/intelmq/intelmq/lib/test.py", line 363, in assertMessageEqual
    event = self.get_output_queue()[queue_pos]
IndexError: list index out of range

======================================================================
ERROR: intelmq.tests.bots.outputs.xmpp.test_output (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/usr/lib/python3.4/unittest/case.py", line 577, in run
    testMethod()
  File "/usr/lib/python3.4/unittest/loader.py", line 32, in testFailure
    raise exception
ImportError: Failed to import test module: intelmq.tests.bots.outputs.xmpp.test_output
Traceback (most recent call last):
  File "/usr/lib/python3.4/unittest/loader.py", line 312, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.4/unittest/loader.py", line 290, in _get_module_from_name
    __import__(name)
  File "/home/intelmq/intelmq/intelmq/tests/bots/outputs/xmpp/test_output.py", line 5, in <module>
    import intelmq.bots.outputs.xmpp.output
  File "/home/intelmq/intelmq/intelmq/bots/outputs/xmpp/output.py", line 84, in <module>
    class XMPPClient(sleekxmpp.ClientXMPP):
AttributeError: 'NoneType' object has no attribute 'ClientXMPP'


======================================================================
FAIL: test_fqdn_to_ip (intelmq.tests.lib.test_harmonization.TestHarmonization)
Test FQDN.to_ip
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/intelmq/intelmq/intelmq/tests/lib/test_harmonization.py", line 214, in test_fqdn_to_ip
    self.assertEqual(None, harmonization.FQDN.to_ip('localhost'))
AssertionError: None != '127.0.0.1'

----------------------------------------------------------------------
Ran 487 tests in 30.856s

FAILED (failures=1, errors=6, skipped=12)
```

**Comment by dmth** [comment] 2016-09-27 10:42
Hi, thanks for reporting.

which installation instructions did you follow (url please).

Some test fail, because you might not have installed the dependencies for the Bots (rt, n6, blueliv, xmpp)

**Comment by sashank** [comment] 2016-09-27 10:45
I just got via "git cloned https://github.com/certtools/intelmq.git"

**Comment by sebix** [comment] 2016-09-27 19:06
You do not have optional packages installed (sleekxmpp, python-rt and stomp.py).

We should not fail in these cases, but skip them.

**Comment by sashank** [comment] 2016-09-28 03:21
Yes , either the INSTALL instructions could be updated to install these packages or the test framework should skip/ignore them if not found and not needed as mandatory

**Comment by sashank** [comment] 2016-09-28 03:22
accidentally closed it , not sure if i should keep it open

**Comment by sebix** [comment] 2016-09-28 06:06
Yes, please keep it open.

**Comment by sebix** [comment] 2016-10-03 09:51
Two failures are because you seem to have no networking:
* intelmq.tests.bots.experts.gethostbyname.test_expert.TestGethostbynameExpertBot.test
* intelmq.tests.lib.test_harmonization.TestHarmonization.test_fqdn_to_ip

and thus duplicate of #687 

the others should be fixed now.

**Closed** 2016-10-03 09:51 UTC
Labels: bug, component: tests
