### ISSUE TITLE
ENH: Error Handling

### ISSUE THREAD

**Issue by SYNchroACK** [certtools/intelmq#326] opened 2015-09-15 11:36 UTC
```
2015-09-15 12:26:31,922 - hphosts-parser - INFO - Pipeline ready.
2015-09-15 12:26:31,922 - hphosts-parser - INFO - Start processing.
2015-09-15 12:26:31,922 - hphosts-parser - DEBUG - Receiving Message.
2015-09-15 12:26:50,997 - hphosts-parser - DEBUG - Receive message u'{"raw": "IyBocEhvc3RzIGxhc3QgdXBkYXRlZCBvbjoJCTIxLzA4LzIwMTUNCiMgaHBIb3N0cyBsYXN0IHZlcmlmaWVkIGJ5IFN0ZXZlbiBCdXJuOgkyMS8wOC8yMDE1DQojDQojIElNUE9SVEFOVDoJUmVuYW1lIHRoaXMgZmlsZSB0byAiSE9TVFMiIChubyAudHh0IGV4dGVuc2lvbikNCiMNCiMgU3VwcG9ydDoJaHR0cDovL215c3RlcnlmY20uY28udWsvP21vZGU9Y29udGFjdA0KIwkJaHR0cDovL2ZvcnVtLmhvc3RzLWZpbGUubmV0DQojDQojIERvd25sb2FkOglodHRwOi8vaG9zdHMtZmlsZS5uZXQvP3M9RG93bmxvYWQNCiMgTWlycm9yczoJaHR0cDovL2hvc3RzLWZpbGUubmV0Lz9zPUhlbHAjZGxtaXJyb3JzDQojDQojIEludGVybWl0dGVudCB1cGRhdGV'...
2015-09-15 12:26:58,873 - hphosts-parser - ERROR - Bot has found a problem.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/intelmq-1.0.0-py2.7.egg/intelmq/lib/bot.py", line 117, in start
    self.process()
  File "/usr/lib/python2.7/site-packages/intelmq-1.0.0-py2.7.egg/intelmq/bots/parsers/hphosts/parser.py", line 45, in process
    event.add("source.fqdn", values[1], sanitize=True)
  File "/usr/lib/python2.7/site-packages/intelmq-1.0.0-py2.7.egg/intelmq/lib/message.py", line 108, in add
    raise exceptions.InvalidValue(key, value, reason=valid_value[1])
InvalidValue: invalid value u'-ads.avast.dwnldfr.com' (<type 'unicode'>) for key u'source.fqdn'regex did not match.
2015-09-15 12:26:58,875 - hphosts-parser - INFO - Bot will restart in 15 seconds.
2015-09-15 12:27:13,889 - hphosts-parser - INFO - Bot woke up
2015-09-15 12:27:13,890 - hphosts-parser - INFO - Trying to start processing again.
2015-09-15 12:27:13,890 - hphosts-parser - DEBUG - Receiving Message.
2015-09-15 12:27:15,603 - hphosts-parser - DEBUG - Receive message u'{"raw": "IyBocEhvc3RzIGxhc3QgdXBkYXRlZCBvbjoJCTIxLzA4LzIwMTUNCiMgaHBIb3N0cyBsYXN0IHZlcmlmaWVkIGJ5IFN0ZXZlbiBCdXJuOgkyMS8wOC8yMDE1DQojDQojIElNUE9SVEFOVDoJUmVuYW1lIHRoaXMgZmlsZSB0byAiSE9TVFMiIChubyAudHh0IGV4dGVuc2lvbikNCiMNCiMgU3VwcG9ydDoJaHR0cDovL215c3RlcnlmY20uY28udWsvP21vZGU9Y29udGFjdA0KIwkJaHR0cDovL2ZvcnVtLmhvc3RzLWZpbGUubmV0DQojDQojIERvd25sb2FkOglodHRwOi8vaG9zdHMtZmlsZS5uZXQvP3M9RG93bmxvYWQNCiMgTWlycm9yczoJaHR0cDovL2hvc3RzLWZpbGUubmV0Lz9zPUhlbHAjZGxtaXJyb3JzDQojDQojIEludGVybWl0dGVudCB1cGRhdGV'...
2015-09-15 12:27:19,485 - hphosts-parser - ERROR - Bot has found a problem.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/intelmq-1.0.0-py2.7.egg/intelmq/lib/bot.py", line 117, in start
    self.process()
  File "/usr/lib/python2.7/site-packages/intelmq-1.0.0-py2.7.egg/intelmq/bots/parsers/hphosts/parser.py", line 45, in process
    event.add("source.fqdn", values[1], sanitize=True)
  File "/usr/lib/python2.7/site-packages/intelmq-1.0.0-py2.7.egg/intelmq/lib/message.py", line 108, in add
    raise exceptions.InvalidValue(key, value, reason=valid_value[1])
InvalidValue: invalid value u'-ads.avast.dwnldfr.com' (<type 'unicode'>) for key u'source.fqdn'regex did not match.
2015-09-15 12:27:19,486 - hphosts-parser - INFO - Bot will restart in 15 seconds.
2015-09-15 12:27:34,501 - hphosts-parser - INFO - Bot woke up
2015-09-15 12:27:34,501 - hphosts-parser - INFO - Trying to start processing again.
2015-09-15 12:27:34,501 - hphosts-parser - DEBUG - Receiving Message.
2015-09-15 12:27:35,917 - hphosts-parser - DEBUG - Receive message u'{"raw": "IyBocEhvc3RzIGxhc3QgdXBkYXRlZCBvbjoJCTIxLzA4LzIwMTUNCiMgaHBIb3N0cyBsYXN0IHZlcmlmaWVkIGJ5IFN0ZXZlbiBCdXJuOgkyMS8wOC8yMDE1DQojDQojIElNUE9SVEFOVDoJUmVuYW1lIHRoaXMgZmlsZSB0byAiSE9TVFMiIChubyAudHh0IGV4dGVuc2lvbikNCiMNCiMgU3VwcG9ydDoJaHR0cDovL215c3RlcnlmY20uY28udWsvP21vZGU9Y29udGFjdA0KIwkJaHR0cDovL2ZvcnVtLmhvc3RzLWZpbGUubmV0DQojDQojIERvd25sb2FkOglodHRwOi8vaG9zdHMtZmlsZS5uZXQvP3M9RG93bmxvYWQNCiMgTWlycm9yczoJaHR0cDovL2hvc3RzLWZpbGUubmV0Lz9zPUhlbHAjZGxtaXJyb3JzDQojDQojIEludGVybWl0dGVudCB1cGRhdGV'...
2015-09-15 12:27:40,231 - hphosts-parser - ERROR - Bot has found a problem.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/intelmq-1.0.0-py2.7.egg/intelmq/lib/bot.py", line 117, in start
    self.process()
  File "/usr/lib/python2.7/site-packages/intelmq-1.0.0-py2.7.egg/intelmq/bots/parsers/hphosts/parser.py", line 45, in process
    event.add("source.fqdn", values[1], sanitize=True)
  File "/usr/lib/python2.7/site-packages/intelmq-1.0.0-py2.7.egg/intelmq/lib/message.py", line 108, in add
    raise exceptions.InvalidValue(key, value, reason=valid_value[1])
InvalidValue: invalid value u'-ads.avast.dwnldfr.com' (<type 'unicode'>) for key u'source.fqdn'regex did not match.
2015-09-15 12:27:40,778 - hphosts-parser - INFO - Disconnecting from source pipeline.
2015-09-15 12:27:40,778 - hphosts-parser - INFO - Disconnecting from destination pipeline.
2015-09-15 12:27:40,778 - hphosts-parser - INFO - Bot stopped.
2015-09-15 12:27:40,778 - hphosts-parser - ERROR - Exiting.
2015-09-15 12:27:40,779 - hphosts-parser - INFO - Bot stopped.
2015-09-15 12:27:40,779 - hphosts-parser - ERROR - Exiting.
```

**Comment by sebix** [comment] 2015-09-15 11:44
Obviously, `'-ads.avast.dwnldfr.com'` is not a valid FQDN. Could be a parser issue or bad input data.

**Comment by SYNchroACK** [comment] 2015-09-19 19:03
@sebix lol, now I found the reason you said that hehee:

check this -> https://github.com/certtools/intelmq/blob/master/intelmq/lib/bot.py#L148

check this 'unofficial' documentation: https://github.com/certtools/intelmq/issues/289

In my perspective, the difference between retry and pass is if bot will retry X times or not but never stops...

so, whats your opinion about this?  (im not sure if my approach is the better for the solution....)

**Comment by sebix** [comment] 2015-09-21 08:58
What does the InvalidValue Error have to do with the Error handling of the bot? Please provide the message, the error occured with. Otherwise, it's hard to find the trigger for this error.

> In my perspective, the difference between retry and pass is if bot will retry X times or not but never stops...

Please write full sentences with a proper english syntax/sentence construction. It is hard to read and interpret your comments.

If the error procedure is retry, the message is processed again until the `error_retries_counter` reaches `error_max_retries`. If `error_dump_message` is true, the message will be dumped. Then the bot dies.

> EDITED: it seems that dump_message didnt occurred

Found this bug, was at https://github.com/certtools/intelmq/blob/master/intelmq/lib/bot.py#L251

**Comment by SYNchroACK** [comment] 2015-09-21 09:16
> What does the InvalidValue Error have to do with the Error handling of the bot? Please provide the message, the error occured with. Otherwise, it's hard to find the trigger for this error.

The message is the whole hp-hosts report. The problem here is not the exception, is the error handling. As I mentioned #289 is explaining the behavior for each parameter and in this case, the implementation is not the same as described in that documentation.

Conclusion: from what I see in code, the bot is behaving correctly but from in my opinion, bot should retry X times and in the end, dump the message, but never stops.

> 
> > In my perspective, the difference between retry and pass is if bot will retry X times or not but never stops...
> 
> If the error procedure is retry, the message is processed again until the `error_retries_counter` reaches `error_max_retries`. If `error_dump_message` is true, the message will be dumped. Then the bot dies.
> 
> > EDITED: it seems that dump_message didnt occurred
> 
> Found this bug, was at https://github.com/certtools/intelmq/blob/master/intelmq/lib/bot.py#L251

**Comment by SYNchroACK** [comment] 2015-09-22 19:04
> from what I see in code, the bot is behaving correctly but in my opinion, bot should retry X times and in the end, dump the message, but never stops.

@sebix and @aaronkaplan @mauroasilva 
Do you agree?

**Comment by mauroasilva** [comment] 2015-09-23 17:25
Agreed... the bot should retry to process the same message X number of times, if it still fails the message should be logged (if the error_dump_message parameter is true), discarded from the queue and the bot should process the next message in the queue.

**Comment by SYNchroACK** [comment] 2015-09-23 20:51
@mauroasilva yap but I forgot to mention the `exit_on_stop` parameter. I think this parameter was added to allows intelmq admin to choose if bot should stop in case of an error (after retries) or keep processing the next messages. @mauroasilva Make sense, right?

**Comment by mauroasilva** [comment] 2015-09-23 22:55
To be honest I don't really see a use case for it, but I'm always in favor of giving the admins more flexibility so I don't mind the ```exit_on_stop``` parameter.

But, just out of curiosity, is there a good reason why the bot should stop after a fail instead of continuing to process new messages and allowing the admin to insert the message after it is reviewed?

**Comment by SYNchroACK** [comment] 2015-09-23 22:57
https://github.com/SYNchroACK/intelmq/blob/master/intelmq/lib/bot.py#L49
https://github.com/SYNchroACK/intelmq/blob/master/intelmq/lib/bot.py#L159
https://github.com/SYNchroACK/intelmq/blob/master/intelmq/lib/bot.py#L210
https://github.com/SYNchroACK/intelmq/blob/master/intelmq/lib/bot.py#L329

**Comment by mauroasilva** [comment] 2015-09-23 23:07
Use your words... lol

But now really... I didn't get that post

**Comment by SYNchroACK** [comment] 2015-09-23 23:13
looooooooooool, crazy stuff. lets use code xD "code is code, no space for interpretation, unless you were a compiler"

https://github.com/certtools/intelmq/compare/master...SYNchroACK:error_handling

**Comment by sebix** [comment] 2015-09-24 08:11
Actually the issue is a duplicate of #289

**Comment by SYNchroACK** [comment] 2015-10-27 06:18
#376

**Closed** 2015-10-31 01:26 UTC
Labels: bug, enhancement
