### ISSUE TITLE
Some parameters with default values throw AttributeError when not set

### ISSUE THREAD

**Issue by gethvi** [certtools/intelmq#1580] opened 2020-07-13 13:30 UTC
If I omit some parameters from the configuration (that are supposed to have default values, e.g. `mail_ssl` (`True`) for `intelmq.bots.collectors.mail` and `delimiter` (`,`) for `intelmq.bots.parsers.generic.csv`), I get an AttributeError:

```
Bot has found a problem.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/intelmq/lib/bot.py", line 269, in start
    self.process()
  File "/usr/local/lib/python3.5/dist-packages/intelmq/bots/collectors/mail/lib.py", line 40, in process
    mailbox = self.connect_mailbox()
  File "/usr/local/lib/python3.5/dist-packages/intelmq/bots/collectors/mail/lib.py", line 33, in connect_mailbox
    self.parameters.mail_ssl,
AttributeError: 'Parameters' object has no attribute 'mail_ssl'
```

This is also reason why in #1571 I explicitly mentioned missing `delimiter`.

I only came across `mail_ssl` and `delimiter` lately when I wanted to count on their default value. There might be more parameters with this behavior.

**Comment by wagner-certat** [comment] 2020-07-13 15:51
I think this is a duplicate of #757

**Comment by wagner-certat** [comment] 2020-10-21 15:21
Duplicate of #757

**Closed by wagner-certat** 2020-10-21 15:21 UTC
