### ISSUE TITLE
Output Bot - PostgreSQL message support (event, report)

### ISSUE THREAD

**Issue by SYNchroACK** [certtools/intelmq#259] opened 2015-07-07 13:23 UTC

**Comment by sebix** [comment] 2015-08-20 15:33
The postgresql output support should support reports?

**Comment by aaronkaplan** [comment] 2015-08-20 16:16
On Aug 20, 2015, at 5:33 PM, Sebastian <notifications@github.com> wrote:

> The postgresql output support should support reports?

As far as I can see right now ... report == message class (at the moment), right?

**Comment by sebix** [comment] 2015-08-20 17:01
Yes, but I can't really figure out, how the Reports should be inserted into the DB, as there's only `feed` and `raw`.

**Comment by aaronkaplan** [comment] 2015-08-20 17:03
On Aug 20, 2015, at 7:01 PM, Sebastian <notifications@github.com> wrote:

> Yes, but I can't really figure out, how the Reports should be inserted into the DB, as there's only feed and raw.
> 

hm, I don;t quite understand.
Maybe let's talk about that tomorrow morning?

Best,
a.

**Comment by sebix** [comment] 2015-08-20 19:09
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

On 08/20/2015 07:03 PM, AaronK wrote:
> On Aug 20, 2015, at 7:01 PM, Sebastian <notifications@github.com> wrote:
> > Yes, but I can't really figure out, how the Reports should be
inserted into the DB, as there's only feed and raw.
> hm, I don;t quite understand.
> Maybe let's talk about that tomorrow morning?
While there is technically no real difference between an Event and an
Report, it is used in another way. Reports are the output of collectors
and the input of Parsers. Reports contain raw data from a source with
many data sets. An event itself has only one incident and all data is
parsed and categorized.
In don't see why it should make sense that a report, with unparsed,
dissonant and duplicate data, is the output of intelmq as it is quite
diametrically to the concept and aim of intelmq.
However it is of course supported currently, just create a table with
columns `feed.name`, `feed.url` and `raw`, connect the pipelines
accordingly.
I don't understand this issue.

P.S.: The only difference between Report and Event is, that Event has
two additional methods: `to_dict`, `to_json` and `__hash__`. The hash is
used for deduplication.
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2.0.22 (GNU/Linux)

iQIcBAEBCAAGBQJV1iXIAAoJEBn0X+vcm0Y7uewP/A3bror09EV5oOgqVrUKAVge
8zzyR62w1ARiZUz/qJF8l8xWiGmUx2xTs1Giyjey2W7O9qUrRxdfX6wYJvAKN+2t
62CtXBam+NaPBQgxDdAv/hKNl6/OxM26Lv/SPI4pRrnBRQHvGnrNQoBlNy9E+jjR
+bvzGELBC1oPtP03dcBYcooJGaCNrrmS7ipZ2nxbB7LkrG4NCoCdu6tanl3dj4qC
34p7eMklRsuYcWtrWM9yf/pFWnE6f3LvpirxtJHAZcqydc7uzEZnsvc5Edl5y56Q
e7oJmEOyocuC1YXnsYnL8ZYWjsElwEaHhvvQ914Fi7VU6Mcx0e+jhKQOiW7oGoi1
BW90tRUu4Kj548v7Tklgw8kE5pBfDRyGgApasi/vXwxz6KP4LfyoO4Wgf9q4Tvej
hOZYyaCCR9nViUnRAkBO3cH6cXHkgWfgczYYMrYpCtnp10C6ICcMx19caniXAFNj
NFIPBqPf7+IxV09bA4tH2tVo8C3VsNGS1J+5q90gr/Wvg5u4eBODw2LH91TPUQbb
daR9dcWWBcMsAcP72yyJQwSLtugFoM+9cs6KUNInXHfOH9fPjdXyRDZEJifftt1b
dR9clSGeFjG/XOohy+3SqaL6YPBKuHUBv4AM1dKDbWsVJ6e1wzOdjKaGE63s/4Kr
k15xhc0e7Jlj8lyhX8X8
=8sKg
-----END PGP SIGNATURE-----

**Comment by SYNchroACK** [comment] 2015-08-23 22:07
@sebix , this is a requirement that from long time ago @aaronkaplan make clear that should be added.

The idea is to have a possibility to store in a database the report collected.
If for some reason this is no more needed, for me its ok to forget since every event has the raw field,

@aaronkaplan , whats your input?

**Comment by SYNchroACK** [comment] 2015-08-25 11:10
The current bot already supports the report output. Its ok to close.

**Comment by aaronkaplan** [comment] 2015-08-25 14:21
Actually @sebix is working on one... 

---
Mobile

**Comment by sebix** [comment] 2015-08-25 14:22
Current postgres bot can handle reports without problem. Just create a table with fields 'raw', 'feed.name' and 'feed.url'.

**Comment by SYNchroACK** [comment] 2015-08-25 14:32
I open again the issue because we are not align with same concepts of a report message, event message and incident report means. So... I will keep the issue open and lets see from your ( @sebix and @aaronkaplan  ) harmonization proposal and some extra documentation that will clarify the concepts. ;)

**Comment by sebix** [comment] 2015-09-09 12:22
I still don't understand what the issue is about. @aaronkaplan please clarify what you mean, or close it.

**Comment by SYNchroACK** [comment] 2015-09-11 13:35
@aaronkaplan , what is the status of this issue?

**Comment by sebix** [comment] 2015-10-06 08:46
In the UI this is not possible, as the manager gives this error message when connecting a colelctor to an output bot:

> Node type Collector can only connect to nodes of types: Parser

**Comment by aaronkaplan** [comment] 2015-10-06 08:59
I am utterly confused by this issue lol.

**Comment by aaronkaplan** [comment] 2015-10-06 09:06
Clarified with @sebix now. I think we are all set and we can close this.

**Closed by aaronkaplan** 2015-10-06 09:06 UTC
Labels: enhancement, high priority
