### ISSUE TITLE
Misp parser error

### ISSUE THREAD

**Issue by Roslekas** [certtools/intelmq#965] opened 2017-05-05 13:29 UTC
Every time I got error in "intelmq.lib.exeptions.InvalidValue: invalid value '...........'" with different value, that could it be ?

![image](https://cloud.githubusercontent.com/assets/16913780/25747255/892773ee-31af-11e7-8d92-bb3cb65cf756.png)

![image](https://cloud.githubusercontent.com/assets/16913780/25747296/b381de9a-31af-11e7-9be3-3063d9221df5.png)

Thanks

**Comment by dmth** [comment] 2017-05-05 13:59
Hi,
the parser seems to try to write the string `gethe.php` (1st image) or `krp3mg/images/ into the IntelMQ-Fields `source.url`. But the string is not a valid URL.
That's the reason why this is failing. But I'm not familiar with the MISP parser and cannot tell you why it tries to do this.

BR

**Comment by wagner-certat** [comment] 2017-05-08 08:11
@Roslekas The data in MISP's `url` field is simply not valid. In IntelMQ URLs must not only have a path, but also a host and a protocol. I see that MISP also has a `domain` and `hostname` field, but I'm not sure if they are useful to create a full URL with them. But we don't have a protocol anyway, so it seems we can's use this data for `source.url` then.

ping @Rafiot

**Comment by Rafiot** [comment] 2017-05-12 10:32
As @wagner-certat says, the URL is definitely not valid. The reason is that the URLs aren't validated on MISP (@iglocska: can you confirm?): 
https://github.com/MISP/MISP/blob/d32fc05a35c36042643a7feaf8a22f5d1df15043/app/Model/Attribute.php#L918

**Comment by aaronkaplan** [comment] 2017-05-29 16:23
@iglocska, @Rafiot can you please check ? Thx

**Comment by wagner-certat** [comment] 2017-06-26 15:02
Closing this, as it seems like the problem is invalid data from MISP. Otherwise please reopen.

**Closed** 2017-06-26 15:03 UTC
Labels: bug, component: bots
