### ISSUE TITLE
Wiki Feeds page not showing latest version

### ISSUE THREAD

**Issue by jgedeon120** [certtools/intelmq#797] opened 2016-11-29 12:54 UTC
When using the wiki and looking at the Feeds page it doesn't seem to be the latest version of docs/Feeds.md.

**Comment by sebix** [comment] 2016-11-29 13:01
duplicate of #511

**Comment by aaronkaplan** [comment] 2016-11-29 13:02
thx, known issue. We need to remove the (outdated) wiki. docs/ is the right folder to look at.

**Closed by sebix** 2016-11-29 13:01 UTC
