### ISSUE TITLE
make sure everything is IPv6 ready

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#401] opened 2015-11-17 17:26 UTC
Yeah... it's coming :)

Seriously, actually we do have a few events, which contain IPv6 addresses. Hence the whole pipeline and all bots needs to be able to process IPv6.

So that task at hand is to create a test case for all bots with an IPv6 address.

**Comment by sebix** [comment] 2015-11-17 17:31
Duplicate of #306

**Closed by sebix** 2015-11-17 17:31 UTC
Labels: architecture, duplicate, feature request
