### ISSUE TITLE
deduplicator is too slow

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#685] opened 2016-09-17 10:10 UTC
The rate of the dedup expert is somehow very slow.

## Proposal
  * make a test case with thousands or a couple of million entries, test and identify the bottleneck independently.
  * Then patch

**Comment by dmth** [comment] 2016-09-23 12:53
Did you check if your system started swapping?

**Comment by aaronkaplan** [comment] 2016-09-23 12:55
> On 23 Sep 2016, at 14:53, Dustin Demuth <notifications@github.com> wrote:
> 
> Did you check if your system started swapping?

Yes, it does not since swapping was disabled and I knew that I had enough RAM.

**Comment by dmth** [comment] 2016-09-23 12:56
btw. this is a duplicate of: https://github.com/certtools/intelmq/issues/613

**Closed** 2016-09-23 17:13 UTC
Labels: invalid: duplicate, performance
