### ISSUE TITLE
MISP bot?

### ISSUE THREAD

**Issue by h122015** [certtools/intelmq#537] opened 2016-06-02 12:13 UTC
Hi everybody

I'd like to ask what the current status of the MISP bots is. I've seen a couple of issues regarding integration of MISP into IntelMQ, but I don't know where can I get to code from. If code hasn't yet been committed, when would be expected to release this bot?

Thanks a lot for your reply

**Comment by sebix** [comment] 2016-06-02 14:32
> If code hasn't yet been committed, when would be expected to release this bot?

As soon as someone writes the code.

Closing as duplicate of #279 and #377.

**Closed by sebix** 2016-06-02 14:32 UTC
Labels: invalid: duplicate

**Comment by aaronkaplan** [comment] 2016-06-02 16:57
On Thu, Jun 02, 2016 at 05:13:52AM -0700, h122015 wrote:
> Hi everybody
> 
> I'd like to ask what the current status of the MISP bots is. I've seen a couple of issues regarding integration of MISP into IntelMQ, but I don't know where can I get to code from. If code hasn't yet been committed, when would be expected to release this bot?

Actually we included sample code back into MISP already.
That is one way of the connection.

The other way would be a sort of an expert bot in intelmq which can
query the MISP API and check for existence in MISP and if so, add a MISP
ID field.

Does this sound like what you need?

**Comment by h122015** [comment] 2016-06-06 07:42
Thanks for the feedback. Actually  I was thinking more in terms of having a parser bot as discussed on https://github.com/certtools/intelmq/issues/279. Does the code committed into MISP work as a parser bot?

**Comment by aaronkaplan** [comment] 2016-06-06 07:56
---
Mobile

> On 06.06.2016, at 09:42, h122015 <notifications@github.com> wrote:
> 
> Thanks for the feedback. Actually I was thinking more in terms of having a parser bot as discussed on #279. Does the code committed into MISP work as a parser bot?
> 

No. It is a plugin for MISP to check if an IP address or similar has been seen by intelmq.

**Comment by aaronkaplan** [comment] 2016-06-06 07:59
By the way, when you said MISP parser, I think it is the same as I mean by connector from intelmq to MISP via MISP 's API. 

So I think the way to do this is to have a collector which can connect to MISP and pull the latest events and attributes. 

Yes definitely something I'd like to have. 

---
Mobile

**Comment by h122015** [comment] 2016-06-06 08:01
Exactly, that's what I had in mind. I'll try to code then something like this and let you know if I get this working

**Comment by aaronkaplan** [comment] 2016-06-06 15:12
---
Mobile

> On 06.06.2016, at 10:01, h122015 <notifications@github.com> wrote:
> 
> Exactly, that's what I had in mind. I'll try to code then something like this and let you know if I get this working
> 


Here will be a hackathon at first.org on Sunday. And the main developer of MISP is there. So this might be a good opportunity to get something done efficiently.

**Comment by h122015** [comment] 2016-06-10 12:01
I've coded already the connector, maybe you guys can have a loot at it at the Hackathon at FIRST?

**Comment by aaronkaplan** [comment] 2016-06-10 12:31
We can :)

---
Mobile

**Comment by h122015** [comment] 2016-06-10 12:44
Well, since I have not permission to commit code to your repository, I sent the code to a colleague of mine that is attending FIRST. He mentioned that he's going to meet you there :)

**Comment by aaronkaplan** [comment] 2016-06-10 12:47
---
Mobile

> On 10.06.2016, at 21:44, h122015 <notifications@github.com> wrote:
> 
> Well, since I have not permission to commit code to your repository, I sent the code to a colleague of mine that is attending FIRST. He mentioned that he's going to meet you there :)
> 

Perfect (or you could do a pull request) but yes - er have the hackathon. 

Thanks!!!

**Comment by h122015** [comment] 2016-06-13 07:13
Did you get the code?

**Comment by aaronkaplan** [comment] 2016-06-13 07:29
On Mon, Jun 13, 2016 at 12:13:11AM -0700, h122015 wrote:
> Did you get the code?


thanks, yes!

Did not manage to do everything during the hackathon however. But not
forgotten...

> 
> ---
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/certtools/intelmq/issues/537#issuecomment-225504682

--
