### ISSUE TITLE
Connection to MISP server , Following error..

### ISSUE THREAD

**Issue by SparkyNZL** [certtools/intelmq#998] opened 2017-06-09 07:58 UTC
Hi  

Im trying to get IntelMQ to connect to my MISP server. I am getting the following SSL error, but the SSL cert is valid, bellow is the error in full from IntelMQ-Manager

```python
Bot initialization failed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 844, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/ssl_.py", line 325, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.5/ssl.py", line 377, in wrap_socket
    _context=self)
  File "/usr/lib/python3.5/ssl.py", line 752, in __init__
    self.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 988, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 633, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 630, in urlopen
    raise SSLError(e)
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pymisp/api.py", line 104, in __init__
    response = self.get_recommended_api_version()
  File "/usr/local/lib/python3.5/dist-packages/pymisp/api.py", line 1044, in get_recommended_api_version
    response = session.get(url)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 526, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 513, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 623, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/intelmq-1.0.0.dev7-py3.5.egg/intelmq/lib/bot.py", line 76, in __init__
    self.init()
  File "/usr/local/lib/python3.5/dist-packages/intelmq-1.0.0.dev7-py3.5.egg/intelmq/bots/collectors/misp/collector.py", line 34, in init
    self.parameters.misp_verify)
  File "/usr/local/lib/python3.5/dist-packages/pymisp/api.py", line 118, in __init__
    raise PyMISPError('Unable to connect to MISP ({}). Please make sure the API key and the URL are correct (http/https is required): {}'.format(self.root_url, e))
pymisp.exceptions.PyMISPError: Unable to connect to MISP (https://misp/). Please make sure the API key and the URL are correct (http/https is required): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)
```

**Comment by wagner-certat** [comment] 2017-06-09 09:47
Probably the misp module does use the certificates bundled by requests? (which is different to the OS's bundle)

@Rafiot @iglocska

**Comment by SparkyNZL** [comment] 2017-06-09 09:59
it will be seing the SSL cert presented by Apache, which is a bought SSL certificate from comodo so is globally trusted.

**Comment by wagner-certat** [comment] 2017-06-09 10:52
Could you do with your address:

import requests
requests.get('https://example.com')
and:
requests.get('https://example.com', verify='/path/to/your/certfile')

The path to the cert file depends on your OS, maybe something in
`/etc/ssl/...`

**Comment by Rafiot** [comment] 2017-06-10 14:26
First of all, the URL is definitely wrong: `Unable to connect to MISP (https://misp/).`

**Comment by SparkyNZL** [comment] 2017-06-10 21:42
URL is not wrong, I use that same URL to connect to misp from that same
server for 3 other programs which query my misp installation.

The reason that the program thinks it's wrong is because its failing on the
SSL connection

Thanks

Sent from my spaceship...

On 11/06/2017 2:26 AM, "Raphaël Vinot" <notifications@github.com> wrote:

First of all, the URL is definitely wrong: Unable to connect to MISP (
https://misp/).

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/certtools/intelmq/issues/998#issuecomment-307568347>,
or mute the thread

**Comment by SparkyNZL** [comment] 2017-06-10 21:48
Thanks for that I'll give that a shot today ;)

**Comment by SparkyNZL** [comment] 2017-06-11 00:18
the output from the aboce
>>> import requests
>>> requests.get('https://misp.blar.blar')  <--- This matches what is in my certificate

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 513, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 623, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: ("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)

**Comment by SparkyNZL** [comment] 2017-06-11 00:23
if i do the above with google it i get a 200 returned which is what i would expect. , so it seems it has an issue with they type of SSL cert i have

It for some reason can verify it, even though its from a global CA

**Comment by SparkyNZL** [comment] 2017-06-11 01:07
this is the certificate it wont verify

![image](https://user-images.githubusercontent.com/17818264/27007411-e4ec5672-4ea6-11e7-855e-e409e10e1dff.png)

**Comment by Rafiot** [comment] 2017-06-11 10:05
Right then, for some reason the certificate you're using must be using a new key that isn't in the bundle used by requests. You can find a few options there: http://docs.python-requests.org/en/master/user/advanced/#ssl-cert-verification

The reason it works in your browser is because it comes with it's own list of certificates. You can probably export it from your browser and pass it to requests. The other option is to update the machine you're using to run requests, the certificate bundle you're using most probably have a new version available.

**Comment by wagner-certat** [comment] 2017-06-12 10:08
On 06/11/2017 12:05 PM, Raphaël Vinot wrote:
>
> The reason it works in your browser is because it comes with it's own
> list of certificates.
>
The requests packages provided by the distributions remove this and
replace it with the system's bundle.
In intelmq you can give the parameter `http_verify_cert` the full path
to the bundle (see
https://github.com/certtools/intelmq/blob/893aa04e58cd634f31e3b3316bd3882d47bbd72b/docs/Bots.md#collectors),
tough that's (currently) not used by the misp bots (would be nice if we
could do this).

**Comment by wagner-certat** [comment] 2017-06-26 15:05
It seems the problem is not intelmq. Closing this.

Please consider using the [intelmq-users](https://lists.cert.at/cgi-bin/mailman/listinfo/intelmq-users) list for support, not the bug tracker. Thanks!

**Closed by wagner-certat** 2017-06-26 15:05 UTC
Labels: component: bots
