### ISSUE TITLE
error reporting: if some parser / bot fails, have the possibility to email the errors

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#418] opened 2015-12-18 10:42 UTC
Having the errors in the log file is nice, but our NOC team says we'd like to be notified actively.
Think about a mechanism how to alert NOC team handlers of stack traces / error messages so that
 1. we know that it's happening
 2. the NOC team gets overloaded with too many stack traces. So, please aggregate it.

**Comment by sebix** [comment] 2015-12-18 13:53
duplicate of #417

**Closed by sebix** 2015-12-18 13:53 UTC
Labels: invalid
