### ISSUE TITLE
stop bot problems

### ISSUE THREAD

**Issue by shirio57** [certtools/intelmq#463] opened 2016-03-18 21:48 UTC
When I stop the botnet, every bots are stopped but the process of every bots is still running.
What can solve this ?

OS: red hat 7

**Comment by shirio57** [comment] 2016-03-23 10:50
Problem found.
I try to kill a bot via "sudo htop" and using SIGINT as it is in the intelmqctl and it doesn't work.
Is it possible to change it ?

**Comment by sebix** [comment] 2016-03-29 10:00
Was the process running as user intelmq (or root)? What does the log of the bot show?

**Comment by shirio57** [comment] 2016-03-29 12:39
Nothing on the log, last line is bot is starting

I start the botnet with manager GUI so with "sudo -u intelmq /usr/local/bin/intelmqctl %s" so it should be intelmq as user.
When I do "ps -u intelmq" I have all the bots.
When I try to stop them by the manager there are still running. And even after by command line.

It is only when I do everything by command line that I can start and stop everything correctly.

**Comment by sebix** [comment] 2016-03-29 12:52
Ok, it's the manager. Probably duplicate of certtools/intelmq-manager#42
Unfortunately I can't test this on red hat systems.

@mauroasilva can you have a look?

**Comment by sebix** [comment] 2016-04-05 09:22
duplicate of #411

**Closed by sebix** 2016-04-05 09:22 UTC
Labels: bug, component: intelmqctl, duplicate, support
