### ISSUE TITLE
Bots should create the pidfile themselves

### ISSUE THREAD

**Issue by sebix** [certtools/intelmq#689] opened 2016-09-17 12:02 UTC
Currently the ctl tool writes the pidfile. Better the bot itself write it after successful initialization (e.g. after logger has been initialized) and remove it when bot is shutdown.

The latter is also bugfix.

**Comment by aaronkaplan** [comment] 2016-10-05 16:56
Duplicate of #710

**Closed by aaronkaplan** 2016-10-05 16:56 UTC
Labels: bug, component: core, component: intelmqctl
