### ISSUE TITLE
12:54 AM 7נError loading bot log information: [31mLog path not found: /opt/intelmq/var/log/MongoDB-Output.log[0m

### ISSUE THREAD

**Issue by qasidali861** [certtools/intelmq#2261] opened 2022-11-14 06:56 UTC
I am using the MongoDB output bot. So getting this error.
I am getting the same error while using ELK and Files output bot.

**Comment by qasidali861** [comment] 2022-11-14 11:15
@sebix @waldbauer-certat

**Comment by sebix** [comment] 2022-11-14 11:17
Did these bots ever start? What does `intelmqctl start MongoDB-Output` show?

**Comment by qasidali861** [comment] 2022-11-14 11:20
The bot start and than that error start popping.

2022-11-14T11:19:11.727000	MongoDB-Output	INFO	MongoDBOutputBot initialized with id MongoDB-Output and intelmq 3.0.2 and python 3.9.2 (default, Feb 28 2021, 17:03:44) as process 75336.	
2022-11-14T11:19:11.727000	MongoDB-Output	INFO	Bot is starting.


These are the logs.

**Comment by sebix** [comment] 2022-11-14 11:21
Okay, we need a bit more information: `intelmqctl run --loglevel DEBUG MongoDB-Output`

**Comment by qasidali861** [comment] 2022-11-14 11:23
/opt/intelmq/var/log/MongoDB-Output.log

I have check manually and there is now such path exists.

**Comment by qasidali861** [comment] 2022-11-14 11:26
intelmqctl run --loglevel DEBUG MongoDB-Output

Where I need to run this one?

**Comment by sebix** [comment] 2022-11-14 11:31
Just on the command line, same as other `intelmqctl` commands

**Comment by qasidali861** [comment] 2022-11-14 11:34
intelmqctl run --loglevel DEBUG MongoDB-Output
intelmqctl: command not found

**Comment by sebix** [comment] 2022-11-14 11:36
That is improbable. A few minutes ago, intelmqctl did exist.

**Comment by qasidali861** [comment] 2022-11-14 11:37
I am using intelMQ manager Docker-Compose.

**Comment by sebix** [comment] 2022-11-14 11:38
Then execute it inside the container.

**Comment by qasidali861** [comment] 2022-11-14 11:43
2022-11-14 11:19:11,727 - MongoDB-Output - INFO - MongoDBOutputBot initialized with id MongoDB-Output and intelmq 3.0.2 and python 3.9.2 (default, Feb 28 2021, 17:03:44) as process 75336.
2022-11-14 11:19:11,727 - MongoDB-Output - INFO - Bot is starting.
2022-11-14 11:19:11,926 - MongoDB-Output - ERROR - Bot initialization failed.
Traceback (most recent call last):
  File "/etc/intelmq/intelmq/lib/bot.py", line 209, in __init__
    self.init()
  File "/etc/intelmq/intelmq/bots/outputs/mongodb/output.py", line 39, in init
    raise MissingDependencyError("pymongo")
intelmq.lib.exceptions.MissingDependencyError: Could not load dependency 'pymongo', please install it with apt/yum/dnf/zypper (possibly named python3-pymongo) or pip3.
2022-11-14 11:19:11,927 - MongoDB-Output - INFO - Bot stopped.
2022-11-14 11:25:33,831 - MongoDB-Output - INFO - MongoDBOutputBot initialized with id MongoDB-Output and intelmq 3.0.2 and python 3.9.2 (default, Feb 28 2021, 17:03:44) as process 75455.
2022-11-14 11:25:33,831 - MongoDB-Output - INFO - Bot is starting.
2022-11-14 11:25:34,034 - MongoDB-Output - INFO - Bot initialization completed.
2022-11-14 11:42:25,649 - MongoDB-Output - INFO - MongoDBOutputBot initialized with id MongoDB-Output and intelmq 3.0.2 and python 3.9.2 (default, Feb 28 2021, 17:03:44) as process 76002.
2022-11-14 11:42:25,649 - MongoDB-Output - INFO - Bot is starting.
2022-11-14 11:42:25,850 - MongoDB-Output - ERROR - Bot initialization failed.
Traceback (most recent call last):
  File "/etc/intelmq/intelmq/lib/bot.py", line 209, in __init__
    self.init()
  File "/etc/intelmq/intelmq/bots/outputs/mongodb/output.py", line 39, in init
    raise MissingDependencyError("pymongo")
intelmq.lib.exceptions.MissingDependencyError: Could not load dependency 'pymongo', please install it with apt/yum/dnf/zypper (possibly named python3-pymongo) or pip3.
2022-11-14 11:42:25,851 - MongoDB-Output - INFO - Bot stopped.

**Comment by qasidali861** [comment] 2022-11-14 11:44
Are you looking for this?

I have also install pymongo already.

**Comment by sebix** [comment] 2022-11-14 11:45
The bot tries to do `import pymongo` and that fails. If it didn't fail, then the error message would be different.

How and where did you install pymongo? inside the container?

**Comment by sebix** [comment] 2022-11-14 11:46
However, the bot should have written logs with the error message, even with the missing dependency.

**Comment by qasidali861** [comment] 2022-11-14 11:58
I think so I have figure it out.
Can you just let me know how can I enter in my docker container?
and than how to install in docker container these packages.

**Comment by sebix** [comment] 2022-11-14 12:00
look at `docker ps` and copy the container id.
then run `docker exec -ti $containerid bash`, you're inside the container.

Run `apt install python3-pymongo`.
Although, I don't know if that is persistent across container restarts. @waldbauer-certat ?

**Comment by qasidali861** [comment] 2022-11-14 12:06
Thanks I got this
I got permission denied. Than use sudo so it's asking for password.
What is the default intelmq password?

**Comment by sebix** [comment] 2022-11-14 12:08
phew, no idea. In this case I also can only relay to @waldbauer-certat

**Comment by qasidali861** [comment] 2022-11-14 12:09
@waldbauer-certat ???
Thanks Sebix <3
For always helping me out whenever I stucked in some problems

**Comment by waldbauer-certat** [comment] 2022-11-14 12:35
Installing packages after a container has been started is not the recommended solution, it fixes the problem temporary, so I would add pymongo to the Dockerfile instructions.

The default intelmq password can be set via environment variables, see [here](https://github.com/certat/intelmq-docker/blob/main/entrypoint.sh#L9-L10).

In case you dont wanna set them, the default will be intelmq:intelmq

**Comment by qasidali861** [comment] 2022-11-14 12:38
intelmq is not in the sudoers file.  This incident will be reported.

Thanks @waldbauer-certat for this
I tried this and got this error

**Comment by waldbauer-certat** [comment] 2022-11-14 12:39
What are you trying to do within the docker container with sudo? Installing the package?

What commands have you executed?

**Comment by qasidali861** [comment] 2022-11-14 12:41
sudo apt install python3-pymongo

Yup installing package
I am trying to install pymongo

without sudo permission got denied

**Comment by waldbauer-certat** [comment] 2022-11-14 12:43
Can you send me the command you're trying to execute?

**Comment by qasidali861** [comment] 2022-11-14 12:44
**sudo apt install python3-pymongo**

**Comment by waldbauer-certat** [comment] 2022-11-14 12:45
I am not able to reproduce, tried it with the latest docker container & worked

**Comment by qasidali861** [comment] 2022-11-14 12:45
i am also using the latest docker container .....

**Comment by waldbauer-certat** [comment] 2022-11-14 12:46
You're sure that you are executing the commands inside the docker container & not on your base system?

**Comment by qasidali861** [comment] 2022-11-14 12:47
@waldbauer-certat If you also add the ElasticSearch as a dependency also will be really appreciated.

**Comment by qasidali861** [comment] 2022-11-14 12:49
![Screenshot from 2022-11-14 17-48-08](https://user-images.githubusercontent.com/78258973/201664344-d07303ba-5075-4104-a967-a7688fb8fc19.png)

**Comment by qasidali861** [comment] 2022-11-14 12:50
I am inside the docker container.
Tried both of the command

**Comment by waldbauer-certat** [comment] 2022-11-14 12:52
Ah, are you using the intelmq-full-dev image?

**Comment by qasidali861** [comment] 2022-11-14 12:54
Yup!!!!!

**Comment by waldbauer-certat** [comment] 2022-11-14 12:55
Ah I see, thats a bug then. The intelmq-full-dev is a contribution & they're not adding intelmq to sudoers. In the CERT.at maintained version we are using root, so thats why i am confused. We also added intelmq to sudoers, so thats why I cant reproduce.

**Comment by qasidali861** [comment] 2022-11-14 12:57
Oooops.....
Any solution for me to continue work?

**Comment by waldbauer-certat** [comment] 2022-11-14 12:58
Add the following to `./docker/intelmq-full-dev/Dockerfile`
```Dockerfile
RUN useradd -d /opt/intelmq -U -s /bin/bash intelmq \
    && adduser intelmq sudo \
    && echo "%sudo ALL=(ALL) NOPASSWD:ALL" >> /opt/sudoers
```

to the Dockerfile & rebuild the container. Then it should work without any problem :)

**Comment by qasidali861** [comment] 2022-11-14 13:31
Thanks @waldbauer-certat 
Will be looking through this in a while and also let you know. How it works. :)

**Comment by qasidali861** [comment] 2022-11-14 13:36
Also for @sebix and @waldbauer-certat 
Any of you can reply

Where to find the config file of my configured bot's.
I tried a lot but did'nt find that. This will also be very helpful.
Because it takes my a lot time to configure again and again when ever I am working on different machine.
Suggest me the config file, either than copy and paste the IntelMQ Manager whole.

**Comment by sebix** [comment] 2022-11-14 16:53
`./example_config/intelmq/etc/` outside the container is mapped to `/opt/intelmq/etc/` inside the container, where the config files reside.

Don't ask me why the directory has been named *example* config, IMO that's a bad name choice, as it's the *actual* config.

**Comment by qasidali861** [comment] 2022-11-15 06:07
HI @sebix @waldbauer-certat 
I just tried again.
Just clone the latest repo and run the docker container. Got the same error again.

MongoDB Log's

2022-11-15 05:51:55,701 - MongoDB-Output - INFO - MongoDBOutputBot initialized with id MongoDB-Output and intelmq 3.0.2 and python 3.9.2 (default, Feb 28 2021, 17:03:44) as process 230.
2022-11-15 05:51:55,701 - MongoDB-Output - INFO - Bot is starting.
2022-11-15 05:51:55,817 - MongoDB-Output - ERROR - Bot initialization failed.
Traceback (most recent call last):
  File "/etc/intelmq/intelmq/lib/bot.py", line 209, in __init__
    self.init()
  File "/etc/intelmq/intelmq/bots/outputs/mongodb/output.py", line 39, in init
    raise MissingDependencyError("pymongo")
intelmq.lib.exceptions.MissingDependencyError: Could not load dependency 'pymongo', please install it with apt/yum/dnf/zypper (possibly named python3-pymongo) or pip3.
2022-11-15 05:51:55,818 - MongoDB-Output - INFO - Bot stopped.


Docker Container Name : certat/intelmq-full -> not certat/intelmq-full-dev I got mistake lasttime it's without dev.

**This is me installing manually and getting the password wrong again tried using sudo**

intelmq@67f83d277b4d:/opt$ sudo apt install python3-pymongo

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for intelmq: 
Sorry, try again.
[sudo] password for intelmq: 


Without sudo got permission error.

**Comment by qasidali861** [comment] 2022-11-15 07:10
Adding one thing more

I have checked the entrypoint.sh   **intelmq-full**

And the username and password are defualt intelmq

But I am wondering why it's is giving me wrong password notification.

**Comment by sebix** [comment] 2022-11-15 07:11
That's a bug: https://github.com/certat/intelmq-docker/issues/17#issuecomment-1314318830

**Comment by qasidali861** [comment] 2022-11-15 07:13
@sebix 
Any idea when it will be resolved? or merged?

**Comment by qasidali861** [comment] 2022-11-15 08:50
@sebix @waldbauer-certat 

I have fixed this issue manually but

Again it's giving me wrong password try again
I am entering intelmq as password while installing manual package.

**Comment by sebix** [comment] 2022-11-15 08:59
> @sebix Any idea when it will be resolved? or merged?

I'm not a maintainer of that repository.



> @sebix @waldbauer-certat
> 
> I have fixed this issue manually but
> 
> Again it's giving me wrong password try again I am entering intelmq as password while installing manual package.

Did you re-build the docker image?

**Comment by qasidali861** [comment] 2022-11-15 09:02
Yes I have rebuild the docker images.

**Comment by qasidali861** [comment] 2022-11-16 05:22
@waldbauer-certat

**Comment by waldbauer-certat** [comment] 2022-11-16 15:50
I've tested the latest pushes to intelmq-docker & everything works now.

**Comment by qasidali861** [comment] 2022-11-16 16:11
@waldbauer-certat 
Can you double check please
I also just tested the latest push.
I am getting the same errors.
1. intelmq -> while manually installing sudo not working as a password.
2. in mongodb logs getting same error python3-pymongo is not installed
3. I am using **intelmq-dev** 


Here are the logs for Mongo


2022-11-16 16:05:30,921 - MongoDB-Output - INFO - MongoDBOutputBot initialized with id MongoDB-Output and intelmq 3.0.2 and python 3.9.2 (default, Feb 28 2021, 17:03:44) as process 189.
2022-11-16 16:05:30,921 - MongoDB-Output - INFO - Bot is starting.
2022-11-16 16:05:31,019 - MongoDB-Output - ERROR - Bot initialization failed.
Traceback (most recent call last):
  File "/etc/intelmq/intelmq/lib/bot.py", line 209, in __init__
    self.init()
  File "/etc/intelmq/intelmq/bots/outputs/mongodb/output.py", line 39, in init
    raise MissingDependencyError("pymongo")
intelmq.lib.exceptions.MissingDependencyError: Could not load dependency 'pymongo', please install it with apt/yum/dnf/zypper (possibly named python3-pymongo) or pip3.
2022-11-16 16:05:31,019 - MongoDB-Output - INFO - Bot stopped.



This is me try to install Mongo Package manually got password error.

intelmq@74ecc8a89f78:/opt$ sudo apt install python3-pymongo

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for intelmq: 
Sorry, try again.
[sudo] password for intelmq:

**Comment by qasidali861** [comment] 2022-11-16 16:13
I am not using the intelmq-full-dev
Using the intelmq-full.

**Comment by qasidali861** [comment] 2022-11-17 01:49
@waldbauer-certat I got this
I think their is some issue with my VM
Just tried locally it's run.

I just could not find how to run **intelmq-full-dev** I was reading 2 or 3 day's ago documentation but for now I could not find it out can you just give me a link will be appreciated. 
@sebix

**Comment by qasidali861** [comment] 2022-11-17 02:14
@sebix @waldbauer-certat 
Which version's of ElasticSearch are supported by IntelMQ. I just read that 7 will work.
I am using 7.10.0. Got connection refused.


Log's for ElasticSearch

2022-11-17 02:03:08,283 - Elasticsearch-Output - INFO - ElasticsearchOutputBot initialized with id Elasticsearch-Output and intelmq 3.0.2 and python 3.9.2 (default, Feb 28 2021, 17:03:44) as process 634.
2022-11-17 02:03:08,283 - Elasticsearch-Output - INFO - Bot is starting.
2022-11-17 02:03:08,370 - Elasticsearch-Output - ERROR - Bot initialization failed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.9/dist-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/elasticsearch/connection/http_urllib3.py", line 237, in perform_request
    response = self.pool.urlopen(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/util/retry.py", line 525, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.9/dist-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.9/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 950, in send
    self.connect()
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f12fa748400>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/intelmq/lib/bot.py", line 209, in __init__
    self.init()
  File "/usr/local/lib/python3.9/dist-packages/intelmq/bots/outputs/elasticsearch/output.py", line 99, in init
    if not self.es.indices.exists(self.elastic_index):
  File "/usr/lib/python3/dist-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/elasticsearch/client/indices.py", line 292, in exists
    return self.transport.perform_request("HEAD", _make_path(index), params=params)
  File "/usr/lib/python3/dist-packages/elasticsearch/transport.py", line 351, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/usr/lib/python3/dist-packages/elasticsearch/connection/http_urllib3.py", line 250, in perform_request
    raise ConnectionError("N/A", str(e), e)
elasticsearch.exceptions.ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x7f12fa748400>: Failed to establish a new connection: [Errno 111] Connection refused) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f12fa748400>: Failed to establish a new connection: [Errno 111] Connection refused)
2022-11-17 02:03:08,371 - Elasticsearch-Output - INFO - Bot stopped.

**Comment by sebix** [comment] 2022-11-17 07:50
"connection refused" does not appear to be a compatibility issue, but rather a networking/configuration problem.

> I just could not find how to run **intelmq-full-dev** I was reading 2 or 3 day's ago documentation but for now I could not find it out can you just give me a link will be appreciated.

What I am doing is:

```bash
git clone https://github.com/certat/intelmq-docker.git
cd intelmq-docker
docker-compose -f docker-compose-dev.yml up --build
```
I don't know if that's the recommended way or not, but it kinda works.

**Comment by qasidali861** [comment] 2022-11-17 09:01
Hi
I got some idea about this.

I want to store the feed locally running ELK. 
Guide me how can I do this.
@waldbauer-certat @sebix

**Comment by sebix** [comment] 2022-11-17 09:58
You can find the documentation of the ES output bot here: https://intelmq.readthedocs.io/en/latest/user/bots.html#elasticsearch-output-bot

**Comment by qasidali861** [comment] 2022-11-17 13:26
Hi @sebix @waldbauer-certat 
I have made changes in in docker-compose.yml file
ElasticSearch is running fine but I am getting again the same error. Connection Refused
the logs are above

### ```
version: "3"
services:
    redis:
        image: redis:latest
        volumes:
            - ./example_config/redis/redis.conf:/usr/local/etc/redis/redis.conf
        command:
            - redis-server
            - /usr/local/etc/redis/redis.conf
        restart: always
        networks:
            - intelmq-internal
    Elasticsearch:
        image: elasticsearch:7.16.2
        container_name: elasticsearch
        restart: always
        volumes:
            - elastic_data:/usr/share/elasticsearch/data/
        environment:
            ES_JAVA_OPTS: "-Xmx256m -Xms256m"
            discovery.type: single-node    
        ports:
            - '9200:9200'
            - '9300:9300'
        networks:
            - elk
    Kibana:
        image: kibana:7.16.2
        container_name: kibana
        restart: always       
        ports:
            - '5601:5601'
        environment:
            - ELASTICSEARCH_URL=http://elasticsearch:9200  
        depends_on:
            - Elasticsearch  
        networks:
            - elk
    nginx:
        image: certat/intelmq-nginx:latest
        restart: always
        ports:
            - 1337:80
        depends_on:
            - intelmq
        networks:
            - intelmq-internal
    intelmq:
        image: certat/intelmq-full:latest
        volumes:
            - ./example_config/intelmq/etc/:/opt/intelmq/etc/
            - ./example_config/intelmq-api/config.json:/etc/intelmq/api-config.json
            - ./intelmq_logs:/opt/intelmq/var/log
            - ./intelmq_output:/opt/intelmq/var/lib/bots
        depends_on:
            - redis
        environment:
            INTELMQ_SOURCE_PIPELINE_BROKER: "redis"
            INTELMQ_PIPELINE_BROKER: "redis"
            INTELMQ_DESTIONATION_PIPELINE_BROKER: "redis"
            INTELMQ_PIPELINE_HOST: redis
            INTELMQ_SOURCE_PIPELINE_HOST: redis
            INTELMQ_DESTINATION_PIPELINE_HOST: redis
            INTELMQ_REDIS_CACHE_HOST: redis
        networks:
            - intelmq-internal

networks:
    intelmq-internal:
        driver: bridge
    elk:

volumes:
    elastic_data: {}
```

**Comment by qasidali861** [comment] 2022-11-21 06:20
Thanks to @sebix and @waldbauer-certat 
Issue Resolved.


Just a one last query.
How can we change the default field names to our own field names?
I checked but didn't find out for this any expert.

**Comment by waldbauer-certat** [comment] 2022-11-21 12:13
What do you mean by default field names? Are you talking about the IDF ( IntelMQ Data Format )?

It might be worth opening another issue/ask on the mailing list as this issue gets out of scope "Error loading bot log information"

**Comment by qasidali861** [comment] 2022-11-21 12:14
yes
Just like that
**feed.provider** so I just want to change it as **provider**

**Comment by waldbauer-certat** [comment] 2022-11-21 12:16
> **feed.provider** so I just want to change it as **provider**

Keep in mind, changing fields like that will break some bots in intelmq. The IDF is the IntelMQ internal data format, so bots will work as expected.

**Comment by qasidali861** [comment] 2022-11-21 12:18
and also need one more information.

**time.obesrvation** field is included while creating raw or it is created without including **time.obesrvation**.

**Comment by qasidali861** [comment] 2022-11-21 12:18
> > **feed.provider** so I just want to change it as **provider**
> 
> Keep in mind, changing fields like that will break some bots in intelmq. The IDF is the IntelMQ internal data format, so bots will work as expected.

Sure Got it

**Comment by sebix** [comment] 2022-11-21 12:20
> **time.obesrvation** field is included while creating raw or it is created without including **time.obesrvation**.

raw is the original data from the data source. `time.source` is an information by the collector ("when the data was observed/fetched by IntelMQ"), so it's not in raw.

**Comment by waldbauer-certat** [comment] 2022-11-21 12:21
> **time.obesrvation** field is included while creating raw or it is created without including **time.obesrvation**.

The IDF is defined in the harmonization.conf and the time.observation is documented here https://github.com/certtools/intelmq/blob/develop/intelmq/etc/harmonization.conf#L354-L357.

**Comment by sebix** [comment] 2022-11-21 12:23
> > **time.obesrvation** field is included while creating raw or it is created without including **time.obesrvation**.
> 
> is documented here https://github.com/certtools/intelmq/blob/develop/intelmq/etc/harmonization.conf#L354-L357.

We also have that information in the actual docs :) https://intelmq.readthedocs.io/en/maintenance/dev/harmonization-fields.html

**Comment by qasidali861** [comment] 2022-11-21 12:33
@sebix 
I understand about both of them things.

I am confuse about the de duplicator   expert.

My question is that

On what basis raw is created in base64 encoding.
Are you processing the feeds extract from the Feed Provider or on what fields raw is depending or it's differentiating from one event to another event or how are you creating raw field.

**Comment by sebix** [comment] 2022-11-21 12:51
raw is before parsing and it's never changed by any bot. you can put the `raw` data into the parser and you should always get the same event.
of course the raw differs for all you messages, otherwise they would be all identical.

for example with a csv file as input, the parser dumps the original comma-separated line in the raw field additionally to parsing the csv data. if the csv file had a header, it will/should also be present in the raw field (otherwise you couldn't re-parse it to get the same result)

**Comment by qasidali861** [comment] 2022-11-21 13:00
Okay so if I summarize.
It got attached to differentiate each event at own?

**Comment by sebix** [comment] 2022-11-21 13:01
Sorry, I don't understand

**Comment by qasidali861** [comment] 2022-11-21 13:10
Let me explain you again.

raw is basically attached  to differentiate each event from one another?

Here let me give you another scenario.

If I run a bot on 6:00AM and  rate_limit is 3600. So it collected the all events from last 3600 second's.

So than I stop and run again bot. So is it able differentiate to filter the last extracted events. and also if we got the raw again same so it will be dropped or not?

**Comment by sebix** [comment] 2022-11-21 13:15
> raw is basically attached to differentiate each event from one another?

No, it's not meant for differentiation, the event data differs by itself anyway. If you don't need it, you can also remove it: https://intelmq.readthedocs.io/en/maintenance/user/FAQ.html#removing-raw-data-for-higher-performance-and-less-space-usage



> If I run a bot on 6:00AM and rate_limit is 3600. So it collected the all events from last 3600 second's.
> 
> So than I stop and run again bot. So is it able differentiate to filter the last extracted events. and also if we got the raw again same so it will be dropped or not?

Use the deduplicator expert after the parsers to remove these duplicates. the dedupliator should ignore the raw-field actually for hashing the events, because syntactical changes in the data (like ; instead of ,) don't change the data itself.

**Closed as completed** 2022-12-22 15:26 UTC
Labels: support
